export const homeObjOne = {
  primary: false,
  lightBg: true,
  imgStart: "",
  lightTopLine: false,
  topLine: "Vigo Corporation",
  lightText: false,
  lightTextDesc: false,
  headLine: "INTO AFRICA AND OUT OF AFRICA MARKETING",
  buttonLabel: "Get Started",
  description: "We can help you sell, faster!",
  img: require("../../image/hm.png"),
  start: "",
  alt: "save money with us!",
};

export const homeObjTwo = {
  primary: false,
  lightBg: true,
  imgStart: "",
  lightTopLine: false,
  topLine: "Vego Corporation",
  lightText: false,
  lightTextDesc: false,
  headLine: "INTO AFRICA AND OUT OF AFRICA MARKETING",
  buttonLabel: "",
  description: "We can help you sell, faster!",
  img: "",
  start: "",
  alt: "save money with us!",
};

export const homeObjThree = {
  primary: false,
  lightBg: false,
  imgStart: "start",
  lightTopLine: false,
  topLine: "Vigo Corporation",
  lightText: false,
  lightTextDesc: false,
  headLine: "INTO AFRICA AND OUT OF AFRICA MARKETING",
  buttonLabel: "Get Started",
  description: "We can help you sell, faster!",
  img: require("../../image/Course.mp4"),
  start: "start",
  alt: "save money with us!",
};

export const homeObjFour = {
  primary: true,
  lightBg: false,
  imgStart: "",
  lightTopLine: true,
  topLine: "Vego Corporation",
  lightText: true,
  lightTextDesc: true,
  headLine: "INTO AFRICA AND OUT OF AFRICA MARKETING",
  buttonLabel: "Get Started",
  description: "We can help you sell, faster!",
  img: require("../../image/Course.mp4"),
  start: "",
  alt: "save money with us!",
};
