export const homeObjOne = {
  primary: false,
  lightBg: true,
  imgStart: "",
  lightTopLine: false,
  topLine: "Vego Corporation",
  lightText: false,
  lightTextDesc: false,
  headLine: "INTO AFRICA AND OUT OF AFRICA MARKETING",
  buttonLabel: "Get Started",
  description: "We can help you sell, faster!",
  img: require("../../image/test.svg"),
  start: "",
  alt: "save money with us!",
};

export const homeObjTwo = {
  primary: false,
  lightBg: true,
  imgStart: "start",
  lightTopLine: false,
  topLine: "Vego Corporation",
  lightText: false,
  lightTextDesc: false,
  headLine: "INTO AFRICA AND OUT OF AFRICA MARKETING",
  buttonLabel: "Get Started",
  description: "We can help you sell, faster!",
  img: require("../../image/dell.jpg"),
  start: "true",
  alt: "save money with us!",
};

export const homeObjThree = {
  primary: true,
  lightBg: true,
  imgStart: "start",
  lightTopLine: true,
  topLine: "Vego Corporation",
  lightText: false,
  lightTextDesc: true,
  headLine: "INTO AFRICA AND OUT OF AFRICA MARKETING",
  buttonLabel: "Get Started",
  description: "We can help you sell, faster!",
  img: require("../../image/phone.svg"),
  start: "start",
  alt: "save money with us!",
};

export const homeObjFour = {
  primary: true,
  lightBg: false,
  imgStart: "",
  lightTopLine: true,
  topLine: "Vego Corporation",
  lightText: true,
  lightTextDesc: true,
  headLine: "INTO AFRICA AND OUT OF AFRICA MARKETING",
  buttonLabel: "Get Started",
  description: "We can help you sell, faster!",
  img: require("../../image/dev.jpg"),
  start: "",
  alt: "save money with us!",
};
